services:
    filelib.renderer.listener:
        class: Xi\Bundle\FilelibBundle\EventListener\RendererListener
        arguments: [ "@xi_filelib.renderer" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    filelib.twig.extension:
        class: Xi\Bundle\FilelibBundle\Twig\Extension\FilelibExtension
        arguments: [ "@xi_filelib", "@xi_filelib.renderer", "@router" ]
        tags:
            -  { name: twig.extension }
